# Configuration for Auto Labeler during pull request
#
# See https://github.com/actions/labeler for file format
# and https://github.com/google/flatbuffers/labels for a list of valid labels
#
# See .github/workflows/label.yml for Github Action workflow script

c#:
  - ./**/*.cs 
  - net/**/*
  - tests/FlatBuffers.Test/**/*
  - tests/FlatBuffers.Benchmarks/**/*
  - src/idl_gen_csharp.cpp

swift:
  - ./**/*.swift
  - swift/**/*
  - tests/FlatBuffers.GRPC.Swift/**/*
  - tests/FlatBuffers.Benchmarks.swift/**/*
  - tests/FlatBuffers.Test.Swift/**/*
  - src/idl_gen_swift.cpp
  - grpc/**/*swift*

typescript:
  - ./**/*.ts
  - src/idl_gen_js_ts.cpp
  - grpc/flatbuffers-js-grpc/**/*.ts

golang:
  - ./**/*.go
  - src/idl_gen_go.cpp

python:
  - ./**/*.py
  - src/idl_gen_python.cpp